---
driver:
  name: vagrant

  provisioner:
    name: chef_zero

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: debian/jessie64

suites:
  - name: default
    run_list:
    - recipe[cas_varnish::default]
    attributes: 
